using System.IO.Compression;
using System.Text;
using AzureCraft.Application.Bicep.Dtos;
using AzureCraft.Application.Bicep.Services;
using AzureCraft.Infrastructure.Bicep.Shared;
using Microsoft.Extensions.Logging;

namespace AzureCraft.Infrastructure.Bicep;

/// <summary>
/// Orchestrates Bicep file generation from a diagram export.
/// Produces main.bicep, main.bicepparam, per-service modules, and a README.
/// </summary>
public sealed class BicepGenerator : IBicepGenerator
{
    private readonly IReadOnlyDictionary<string, IBicepModule> _modules;
    private readonly ILogger<BicepGenerator> _logger;

    public BicepGenerator(
        IEnumerable<IBicepModule> modules,
        ILogger<BicepGenerator> logger)
    {
        _modules = modules.ToDictionary(m => m.ServiceType);
        _logger = logger;
    }

    public Task<BicepGenerationResult> GenerateAsync(
        DiagramExportDto diagram,
        CancellationToken cancellationToken = default)
    {
        var region = diagram.Region ?? "eastus";
        var prefix = diagram.DiagramName
            .Replace(" ", "-")
            .ToLowerInvariant();
        prefix = System.Text.RegularExpressions.Regex.Replace(prefix, @"[^a-z0-9\-]", "");

        var ctx = new BicepTemplateContext
        {
            DiagramName = diagram.DiagramName,
            Region = region,
            AllNodes = diagram.Nodes,
            AllEdges = diagram.Edges,
            ResourcePrefix = prefix,
        };

        // Filter to deployable nodes (skip resource-group, virtual-network handled separately, subnets)
        var serviceNodes = diagram.Nodes
            .Where(n => n.GroupType is null or "")
            .Where(n => n.ServiceType is not "resource-group")
            .ToList();

        // Network nodes
        var vnetNode = diagram.Nodes.FirstOrDefault(n => n.ServiceType == "virtual-network");

        var files = new List<BicepFileDto>();
        var moduleRefs = new List<(string Name, string Path)>();

        // 1. Network module (always if VNet exists)
        if (vnetNode is not null && _modules.TryGetValue("virtual-network", out var vnetModule))
        {
            var content = WrapAsModule("network", vnetModule.Generate(vnetNode, ctx), region);
            files.Add(new BicepFileDto("modules/network.bicep", content));
            moduleRefs.Add(("network", "modules/network.bicep"));
        }

        // 2. Per-service modules
        foreach (var node in serviceNodes)
        {
            if (node.ServiceType == "virtual-network") continue;

            if (!_modules.TryGetValue(node.ServiceType, out var module))
            {
                _logger.LogWarning("No Bicep module for service type {ServiceType}", node.ServiceType);
                continue;
            }

            var moduleName = BicepStringBuilder.SafeName(node.DisplayName);
            var moduleContent = WrapAsModule(moduleName, module.Generate(node, ctx), region);
            var modulePath = $"modules/{moduleName}.bicep";

            files.Add(new BicepFileDto(modulePath, moduleContent));
            moduleRefs.Add((moduleName, modulePath));
        }

        // 3. Private endpoints module (consolidated)
        var peContent = GeneratePrivateEndpoints(serviceNodes, ctx);
        if (!string.IsNullOrWhiteSpace(peContent))
        {
            files.Add(new BicepFileDto("modules/private-endpoints.bicep",
                WrapAsModule("private-endpoints", peContent, region)));
            moduleRefs.Add(("privateEndpoints", "modules/private-endpoints.bicep"));
        }

        // 4. Diagnostic settings module
        var diagContent = GenerateDiagnosticSettings(serviceNodes, ctx);
        if (!string.IsNullOrWhiteSpace(diagContent))
        {
            files.Add(new BicepFileDto("modules/diagnostics.bicep",
                WrapAsModule("diagnostics", diagContent, region)));
            moduleRefs.Add(("diagnostics", "modules/diagnostics.bicep"));
        }

        // 5. main.bicep
        files.Add(new BicepFileDto("main.bicep", GenerateMainBicep(diagram, moduleRefs, region)));

        // 6. main.bicepparam
        files.Add(new BicepFileDto("main.bicepparam", GenerateParams(diagram, region)));

        // 7. README.md
        files.Add(new BicepFileDto("README.md", GenerateReadme(diagram, serviceNodes)));

        // Build zip
        var zipBytes = BuildZip(files, prefix);

        return Task.FromResult(new BicepGenerationResult(files, zipBytes));
    }

    private static string WrapAsModule(string name, string body, string region)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"// Module: {name}");
        sb.AppendLine($"// Auto-generated by AzureCraft");
        sb.AppendLine();
        sb.AppendLine("@description('Azure region for resources')");
        sb.AppendLine($"param location string");
        sb.AppendLine();
        sb.Append(body);
        return sb.ToString();
    }

    private static string GenerateMainBicep(
        DiagramExportDto diagram,
        List<(string Name, string Path)> moduleRefs,
        string region)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// {diagram.DiagramName} — Azure Infrastructure");
        sb.AppendLine("// Generated by AzureCraft");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();

        // Parameters
        sb.AppendLine("@description('Azure region for all resources')");
        sb.AppendLine($"param location string = resourceGroup().location");
        sb.AppendLine();

        // Check if VMs exist (need admin credentials)
        if (diagram.Nodes.Any(n => n.ServiceType == "virtual-machine"))
        {
            sb.AppendLine("@secure()");
            sb.AppendLine("@description('Admin username for VMs')");
            sb.AppendLine("param adminUsername string");
            sb.AppendLine();
            sb.AppendLine("@secure()");
            sb.AppendLine("@description('Admin password for VMs')");
            sb.AppendLine("param adminPassword string");
            sb.AppendLine();
        }

        // Check if SQL exists
        if (diagram.Nodes.Any(n => n.ServiceType == "azure-sql"))
        {
            sb.AppendLine("@secure()");
            sb.AppendLine("@description('SQL Server admin login')");
            sb.AppendLine("param sqlAdminLogin string");
            sb.AppendLine();
            sb.AppendLine("@secure()");
            sb.AppendLine("@description('SQL Server admin password')");
            sb.AppendLine("param sqlAdminPassword string");
            sb.AppendLine();
        }

        // Check if APIM exists
        if (diagram.Nodes.Any(n => n.ServiceType == "api-management"))
        {
            sb.AppendLine("@description('API Management publisher email')");
            sb.AppendLine("param publisherEmail string");
            sb.AppendLine();
            sb.AppendLine("@description('API Management publisher name')");
            sb.AppendLine("param publisherName string");
            sb.AppendLine();
        }

        // Module references
        sb.AppendLine("// === Modules ===");
        sb.AppendLine();

        foreach (var (name, path) in moduleRefs)
        {
            sb.AppendLine($"module {name} './{path}' = {{");
            sb.AppendLine($"  name: '{name}'");
            sb.AppendLine("  params: {");
            sb.AppendLine("    location: location");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string GenerateParams(DiagramExportDto diagram, string region)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using './main.bicep'");
        sb.AppendLine();
        sb.AppendLine($"param location = '{region}'");

        if (diagram.Nodes.Any(n => n.ServiceType == "virtual-machine"))
        {
            sb.AppendLine("param adminUsername = '<vm-admin-username>'");
            sb.AppendLine("param adminPassword = '<vm-admin-password>'");
        }

        if (diagram.Nodes.Any(n => n.ServiceType == "azure-sql"))
        {
            sb.AppendLine("param sqlAdminLogin = '<sql-admin-login>'");
            sb.AppendLine("param sqlAdminPassword = '<sql-admin-password>'");
        }

        if (diagram.Nodes.Any(n => n.ServiceType == "api-management"))
        {
            sb.AppendLine("param publisherEmail = '<publisher-email>'");
            sb.AppendLine("param publisherName = '<publisher-name>'");
        }

        return sb.ToString();
    }

    private static string GeneratePrivateEndpoints(List<ExportNodeDto> nodes, BicepTemplateContext ctx)
    {
        var sb = new StringBuilder();
        foreach (var node in nodes)
        {
            if (!ctx.HasPrivateEndpoint(node.Id)) continue;

            var symbol = BicepStringBuilder.SymbolName(node.DisplayName);
            var pe = PrivateEndpointGenerator.Generate(node, symbol, "dataSubnetId");
            if (!pe.StartsWith("//"))
            {
                sb.AppendLine(pe);
                sb.AppendLine();
            }
        }
        return sb.ToString().TrimEnd();
    }

    private static string GenerateDiagnosticSettings(List<ExportNodeDto> nodes, BicepTemplateContext ctx)
    {
        if (!ctx.HasLogAnalytics) return string.Empty;

        var sb = new StringBuilder();
        foreach (var node in nodes)
        {
            if (node.ServiceType is "log-analytics" or "application-insights" or "entra-id" or "ddos-protection")
                continue;

            var symbol = BicepStringBuilder.SymbolName(node.DisplayName);
            sb.AppendLine(DiagnosticSettingsGenerator.Generate(symbol, node.DisplayName));
            sb.AppendLine();
        }
        return sb.ToString().TrimEnd();
    }

    private static string GenerateReadme(DiagramExportDto diagram, List<ExportNodeDto> serviceNodes)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {diagram.DiagramName}");
        sb.AppendLine();
        sb.AppendLine("Azure infrastructure generated by **AzureCraft**.");
        sb.AppendLine();
        sb.AppendLine("## Prerequisites");
        sb.AppendLine();
        sb.AppendLine("- [Azure CLI](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli)");
        sb.AppendLine("- [Bicep CLI](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install)");
        sb.AppendLine("- An Azure subscription with Contributor access");
        sb.AppendLine();
        sb.AppendLine("## Deploy");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("# Login to Azure");
        sb.AppendLine("az login");
        sb.AppendLine();
        sb.AppendLine("# Create resource group");
        sb.AppendLine($"az group create --name rg-{diagram.DiagramName.Replace(" ", "-").ToLowerInvariant()} --location {diagram.Region ?? "eastus"}");
        sb.AppendLine();
        sb.AppendLine("# Deploy");
        sb.AppendLine($"az deployment group create \\");
        sb.AppendLine($"  --resource-group rg-{diagram.DiagramName.Replace(" ", "-").ToLowerInvariant()} \\");
        sb.AppendLine("  --template-file main.bicep \\");
        sb.AppendLine("  --parameters main.bicepparam");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## Resources");
        sb.AppendLine();
        sb.AppendLine("| Service | Type |");
        sb.AppendLine("|---------|------|");
        foreach (var node in serviceNodes)
        {
            sb.AppendLine($"| {node.DisplayName} | {node.ServiceType} |");
        }
        sb.AppendLine();
        sb.AppendLine("## Important");
        sb.AppendLine();
        sb.AppendLine("1. Update `main.bicepparam` with your actual parameter values before deploying.");
        sb.AppendLine("2. Review all resources and their SKUs to ensure they match your requirements and budget.");
        sb.AppendLine("3. Some resources (e.g., Azure SQL, VMs) require secure credentials — never commit these to source control.");

        return sb.ToString();
    }

    private static byte[] BuildZip(List<BicepFileDto> files, string prefix)
    {
        using var ms = new MemoryStream();
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
        {
            foreach (var file in files)
            {
                var entry = zip.CreateEntry($"{prefix}/{file.Path}", CompressionLevel.Optimal);
                using var writer = new StreamWriter(entry.Open(), Encoding.UTF8);
                writer.Write(file.Content);
            }
        }
        return ms.ToArray();
    }
}
